### PR TITLE
Fix #115: Add ESModule support

### LINKED ISSUE #115: Support ModuleKind.ESModule
When I use `scalajs-bundler` which generates a single bundle with `ModuleKind` as `CommonJSModule`,  I am successfully able to use `SeleniumJSEnv` with `Chrome` for running tests written with `ScalaTest`. 

For a simpler workflows, I do not want to use `scalajs-bunlder` and would like to package the app as an `ESModule`. This works fine when I load it via index.html. 

But, when I try to run `ScalaTest` with `SeleniumJSEnv` and `Chrome`, I get the following error. Is it possible to remove this restriction?

```txt
[debug] > Exec(example-client-js2/test, Some(1bd87d3d-7450-4236-a443-4a8b93ea8f4a), Some(CommandSource(console0)))
[debug] Evaluating tasks: example-client-js2 / Test / test
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug] Global IR cache stats: reused: 230 -- invalidated: 0 -- trees read: 0
[error] org.scalajs.jsenv.UnsupportedInputException: Unsupported input: List(ESModule(/Users/mushtaqahmed/projects/tmt/msocket/example/example-client-js2/target/scala-2.13/example-client-js2-test-fastopt.js))
[error] 	at org.scalajs.jsenv.selenium.SeleniumRun$.$anonfun$startInternal$1(SeleniumRun.scala:134)
[error] 	at scala.collection.immutable.List.map(List.scala:293)
[error] 	at org.scalajs.jsenv.selenium.SeleniumRun$.startInternal(SeleniumRun.scala:132)
[error] 	at org.scalajs.jsenv.selenium.SeleniumRun$.startWithCom(SeleniumRun.scala:122)
[error] 	at org.scalajs.jsenv.selenium.SeleniumJSEnv.startWithCom(SeleniumJSEnv.scala:28)
[error] 	at org.scalajs.testing.adapter.JSEnvRPC.<init>(JSEnvRPC.scala:25)
[error] 	at org.scalajs.testing.adapter.TestAdapter.startManagedRunner(TestAdapter.scala:129)
[error] 	at org.scalajs.testing.adapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:120)
[error] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
[error] 	at org.scalajs.testing.adapter.TestAdapter.getRunnerForThread(TestAdapter.scala:120)
[error] 	at org.scalajs.testing.adapter.TestAdapter.loadFrameworks(TestAdapter.scala:56)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$4(ScalaJSPluginInternal.scala:508)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:233)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:59)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (example-client-js2 / Test / loadedTestFrameworks) org.scalajs.jsenv.UnsupportedInputException: Unsupported input: List(ESModule(/Users/mushtaqahmed/projects/tmt/msocket/example/example-client-js2/target/scala-2.13/example-client-js2-test-fastopt.js))
[error] Total time: 0 s, completed 10 Sep 2020, 17:15:43
[debug] > Exec(shell, None, None)
```

### PR DESCRIPTION
**Pull request by mushtaq**

### CODE REVIEW

**Comment by gzm0** [comment]
Thank you for your contribution. Please sign the Scala CLA: https://www.lightbend.com/contribute/cla/scala in order for us to be able to accept your contribution.

**Comment by gzm0** [comment]
I'm aware this isn't (unfortunately) explicitly written in the readme here, but most (if not all) of the Scala.js main repo [contribution guidelines][1] apply.

[1]: https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md

**Comment by mushtaq** [comment]
@gzm0 I just signed the CLA.

I will go over the guidelines. Will appreciate if you could points a few missing things in the PR to get me started.

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,4 @@
+.idea
```
Comment (gzm0) [inline .gitignore]: This repo does not contain IDE specific `.gitignore` entries. Please put them into your local `.gitignore`.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 2]
```diff
@@ -171,13 +178,14 @@ private[selenium] object SeleniumRun {
   private def maybeCleanupDriver(d: WebDriver, config: SeleniumJSEnv.Config) =
     if (!config.keepAlive) d.close()
 
-  private def htmlPage(scripts: Seq[java.net.URL]): String = {
-    val scriptTags =
-      scripts.map(path => s"<script src='${path.toString}'></script>")
+  private def htmlPage(scripts: Seq[java.net.URL], modules: Seq[java.net.URL]): String = {
+    val scriptTags = scripts.map(path => s"<script src='${path.toString}'></script>")
+    val moduleTags = modules.map(path => s"<script type='module' src='${path.toString}'></script>")
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: This does not preserve the loading order of scripts v.s. modules. The order should be preserved.

**Review by gzm0 — CHANGES_REQUESTED** [review]
Please add a test. At least a superficial one examining the code paths, ideally one that actually loads another module. Note that this needs a webserver, so it should probably go in `seleniumJSHttpEnvTest`.

Please put the commit message in the following form:

> Fix #115: Add ESModule support

**Comment by mushtaq** [comment]
Thanks for the inputs @gzm0. 
Will look into adding a test over the weekend.

**Comment by mushtaq** [comment]
@gzm0 I attempted writing a module import test by mapping JSImport to a CDN entry. Will that be ok?

File: build.sbt [hunk 3]
```diff
@@ -127,13 +137,12 @@ lazy val seleniumJSEnvTest: Project = project.
 lazy val seleniumJSHttpEnvTest: Project = project.
   enablePlugins(ScalaJSPlugin).
   enablePlugins(ScalaJSJUnitPlugin).
-  settings(testSettings).
+  settings(httpTestSettings)
+
+lazy val seleniumJSHttpESModuleEnvTest: Project = project.
```
Comment (gzm0) [inline build.sbt]: You don't necessarily need to create a new project for this. Everything that is tested in `seleniumJSHttpEnvTest` can also be tested in `ESModule` mode.

Either works for me, but if you want the separate project, you should probably materialize it in a different server directory.

Also, it needs to be added to `.travis.yml`.

File: seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala [hunk 4]
```diff
@@ -0,0 +1,10 @@
+package org.scalajs.jsenv.selenium
+
+import scala.scalajs.js
+import scala.scalajs.js.annotation.JSImport
+
+@JSImport("https://cdn.skypack.dev/camelcase@^6.0.0", JSImport.Default)
+@js.native
+object CamelcaseEsModule extends js.Object {
+  def apply(input: String): String = js.native
```
Comment (gzm0) [inline seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: Consider a private native member on the `CamelCase` object directly (you might need to upgrade Scala.js for this).

```scala
object CamelCase {
  def hello(...): String = ...

  @JSImport("https://cdn.skypack.dev/camelcase@^6.0.0", JSImport.Default)  
  @js.native
  private def camelCase(input: String): String = js.native
}
```

File: seleniumJSHttpESModuleEnvTest/src/test/scala/org/scalajs/jsenv/selenium/LocationTest.scala [hunk 5]
```diff
@@ -0,0 +1,14 @@
+package org.scalajs.jsenv.selenium
+
+import org.junit.Assert._
+import org.junit.Test
+
+import scala.scalajs.js.Dynamic.global
+
+class LocationTest {
```
Comment (gzm0) [inline seleniumJSHttpESModuleEnvTest/src/test/scala/org/scalajs/jsenv/selenium/LocationTest.scala]: I don't think we need this test twice. Depending on whether you do the one/two project thing, remove, or it's already there :)

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: build.sbt (hunk 3 above)
Comment (mushtaq) [reply build.sbt]: Ok, happy with a single project with ESModule setting on :)

File: seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala (hunk 4 above)
Comment (mushtaq) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: Sure, I think this came in at version 1.1.0. Should I upgrade to that one or go all the way up to 1.2.0?

File: seleniumJSHttpESModuleEnvTest/src/test/scala/org/scalajs/jsenv/selenium/LocationTest.scala (hunk 5 above)
Comment (mushtaq) [reply seleniumJSHttpESModuleEnvTest/src/test/scala/org/scalajs/jsenv/selenium/LocationTest.scala]: Sure, will not be a problem once I use a single project.

File: seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala (hunk 4 above)
Comment (gzm0) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: Just create an additional commit that upgrades to the newest Scala.js version. Like this:

https://github.com/scala-js/scala-js-env-selenium/commit/934597103b5ee6185705d928db95f1383de99c34

Comment (gzm0) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: (can be in the same PR)

Comment (mushtaq) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: I mean to ask, in that commit, should I upgrade to 1.2.0 or 1.1.0? 
I am not aware of compatibility requirements of this project, hence the question.

Comment (gzm0) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: Just upgrade to the newest version, so 1.2.0. This project does not publish anything that has a dependency on the Scala.js (core). It only has a dependency on `scalajs-jsenv` (which is "below" the core in the dependency trees).

So upgrading Scala.js in this repo does not impose any upgrades on downstream projects.

Comment (gzm0) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: I just realized: We have a bug in our build on these lines: https://github.com/scala-js/scala-js-env-selenium/blob/v1.0.0/build.sbt#L81-L82


`scalajs-js-envs` is *not* release together with Scala.js (anymore). So using the `scalaJSVersion` there does not make any sense. Either hardcode it or introduce `val jsEnvsVersion` (local to the build).

Comment (mushtaq) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: So just to be clear, 
- Upgrade Scala.js in [this line](https://github.com/scala-js/scala-js-env-selenium/blob/master/project/build.sbt#L1) to `1.2.0` and
- Upgrade scala-js-env in [these lines](https://github.com/scala-js/scala-js-env-selenium/blob/v1.0.0/build.sbt#L81-L82) to `1.1.1` (as there is no 1.2.0 version of it)

Right?

Comment (sjrd) [reply seleniumJSHttpESModuleEnvTest/src/main/scala/org/scalajs/jsenv/selenium/CamelcaseEsModule.scala]: Yes, that is correct.

**Comment by mushtaq** [comment]
Done with the version upgrade and ESModule setting on by default.

File: build.sbt [hunk 6]
```diff
@@ -64,6 +64,17 @@ val testSettings: Seq[Setting[_]] = commonSettings ++ Seq(
   scalaJSUseMainModuleInitializer := true
 )
 
+val httpTestSettings: Seq[Setting[_]] = testSettings ++ Seq(
```
Comment (gzm0) [inline build.sbt]: The factoring into a separate val is now not really necessary anymore.

File: seleniumJSHttpEnvTest/src/test/scala/org/scalajs/jsenv/selenium/CamelCaseTest.scala [hunk 7]
```diff
@@ -0,0 +1,10 @@
+package org.scalajs.jsenv.selenium
+
+import org.junit.Assert._
+import org.junit.Test
+
+class CamelCaseTest {
```
Comment (gzm0) [inline seleniumJSHttpEnvTest/src/test/scala/org/scalajs/jsenv/selenium/CamelCaseTest.scala]: I didn't notice it before: But I think we should give this a name that describes what it tests, not what it does.

So maybe: `ModuleSupportTest` and call the test `testBasicImport`. (notice that different casing, according to Scala.js style).

The rationale here is that failures are easier to understand. Compare:

"failed: CamelCaseTest" to "failed: ModuleSupportTest".

In the second case, it hints that there is a problem with module support (which might be the case). In the first case, it hints that there is a problem with camel casing, which isn't a functionality provided by this repo.

**Review by gzm0 — CHANGES_REQUESTED** [review]
Only minor nits. LG otherwise.

Once done, please put the changes in two commits: one with the version changes, one with the fix for module support. 

In the one with the version changes, please put a short explanation into the commit body, why you are not re-using `scalaJSVersions`. (feel free to reference http://www.scala-js.org/news/2020/07/02/announcing-scalajs-1.1.1/).

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 8]
```diff
@@ -171,13 +163,25 @@ private[selenium] object SeleniumRun {
...
-  private def htmlPage(scripts: Seq[java.net.URL]): String = {
-    val scriptTags =
-      scripts.map(path => s"<script src='${path.toString}'></script>")
+  private def htmlPage(setupJsUrl: URL, input: Seq[Input], materializer: FileMaterializer): String = {
+    val setupJs = s"<script src='${setupJsUrl.toString}'></script>"
+
+    val tags = input.map {
+      case Input.Script(path) =>
+        val url = materializer.materialize(path)
+        s"<script src='${url.toString}'></script>"
```
Comment (sjrd) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: In the HTML builder for `testHtml` we use the `defer` attribute on the script tags (both for script and module):
https://github.com/scala-js/scala-js/blob/6398685a38a0f64bfde154bfdd5b8f0d54888ae9/test-adapter/src/main/scala/org/scalajs/testing/adapter/HTMLRunnerBuilder.scala#L68
It was necessary to guarantee the proper order of execution when there are mixed scripts and modules. I'm pretty sure it is necessary here as well.

**Comment by mushtaq** [comment]
I have incorporated all the suggestions so far. Thank you.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 9]
```diff
@@ -171,18 +163,31 @@ private[selenium] object SeleniumRun {
...
-  private def htmlPage(scripts: Seq[java.net.URL]): String = {
-    val scriptTags =
-      scripts.map(path => s"<script src='${path.toString}'></script>")
+  private def htmlPage(setupJsUrl: URL, input: Seq[Input], materializer: FileMaterializer): String = {
+    val setupJs = s"<script src='${setupJsUrl.toString}'></script>"
+
+    val tags = input.map {
+      case Input.Script(path) => makeTag(path, "text/javascript", materializer)
+      case Input.ESModule(path) => makeTag(path, "module", materializer)
+      case _ => throw new UnsupportedInputException(input)
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: Align the arrows? (see https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#pattern-matching)

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 10]
```diff
@@ -171,18 +163,31 @@ private[selenium] object SeleniumRun {
   private def maybeCleanupDriver(d: WebDriver, config: SeleniumJSEnv.Config) =
     if (!config.keepAlive) d.close()
 
-  private def htmlPage(scripts: Seq[java.net.URL]): String = {
-    val scriptTags =
-      scripts.map(path => s"<script src='${path.toString}'></script>")
+  private def htmlPage(setupJsUrl: URL, input: Seq[Input], materializer: FileMaterializer): String = {
+    val setupJs = s"<script src='${setupJsUrl.toString}'></script>"
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: Consider adding defer (and maybe even use `makeTag`) for consistency.

**Review by gzm0 — APPROVED** [review]

**Comment by gzm0** [comment]
@sjrd further comments on this?

**Comment by sjrd** [comment]
I have nothing else to add :)

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 11]
```diff
@@ -171,18 +163,31 @@ private[selenium] object SeleniumRun {
   private def maybeCleanupDriver(d: WebDriver, config: SeleniumJSEnv.Config) =
     if (!config.keepAlive) d.close()
 
-  private def htmlPage(scripts: Seq[java.net.URL]): String = {
-    val scriptTags =
-      scripts.map(path => s"<script src='${path.toString}'></script>")
+  private def htmlPage(setupJsPath: Path, input: Seq[Input], materializer: FileMaterializer): String = {
+    val setupJs = makeTag(setupJsPath, "text/javascript", materializer)
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: Hum, am I misunderstanding this now, or would this copy the setup script twice?

If you are looking for ways to consolidate code and the fact that the setup script is not a `Path` is problematic, I think it would be OK to add Jimfs as a dependency and make in-memory `Path`s. There is precedent for this in the Node.js env: https://github.com/scala-js/scala-js-js-envs/blob/v1.1.1/nodejs-env/src/main/scala/org/scalajs/jsenv/nodejs/ComSupport.scala#L247

Comment (mushtaq) [reply seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: Done. Let me know if I got it right.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 12]
```diff
@@ -129,20 +131,10 @@ private[selenium] object SeleniumRun {
...
       withCleanup(FileMaterializer(config.materialization))(_.close()) { m =>
-        val allScriptURLs = (
-            m.materialize("setup.js", JSSetup.setupCode(enableCom)) +:
-            scripts.map(m.materialize)
-        )
-
-        val page = m.materialize("scalajsRun.html", htmlPage(allScriptURLs))
-
+        val setupJsPath = JSSetup.setupFile(enableCom)
+        val page = m.materialize("scalajsRun.html", htmlPage(setupJsPath, input, m))
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: At this point, you can just pass this as additional input:

```scala
val fullInput = Input.Script(JSSetup.setupFile(enableCom)) :: input
/* snip */ htmlPage(fullInput, m) /* snip */
```

That'll also simplify `htmlPage`.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/JSSetup.scala [hunk 13]
```diff
@@ -1,80 +1,88 @@
...
-     |    send: function(msg) {
-     |      if (inMessages !== null) inMessages.push(msg);
-     |      else onMessage(msg);
-     |    }
-     |  };
-     |}).call(this)
-    """.stripMargin
+  def setupFile(enableCom: Boolean): Path = {
+    Files.write(
+      Jimfs.newFileSystem().getPath("setup.js"),
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/JSSetup.scala]: Scala.js style guide demands that this be indented by 4 spaces (continuation line).

Consider:

```scala
val code = {
  s"""
  /* snip */
  """.stripMargin
}

Files.write(
    Jimfs.newFileSystem().getPath("/setup.js"),
    code.getBytes(StandardCharset.UTF_8))
```

To avoid having to indent the huge string literal too much.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala [hunk 14]
```diff
@@ -171,18 +163,31 @@ private[selenium] object SeleniumRun {
...
-       |    ${scriptTags.mkString("\n    ")}
+       |    ${allTags.mkString("\n    ")}
        |  </body>
        |</html>
     """.stripMargin
   }
 
+  private def makeTag(path: Path, tpe: String, materializer: FileMaterializer): String = {
+    val url = materializer.materialize(path)
+    s"<script defer type='$tpe' src='${url.toString}'></script>"
```
Comment (gzm0) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumRun.scala]: Also just noticed this: You can drop the `toString` (and hence the braces). It's implied by the `s` interpolator.

**Review by gzm0 — CHANGES_REQUESTED** [review]

**Review by gzm0 — APPROVED** [review]

**Comment by gzm0** [comment]
Thank you!

**Comment by mushtaq** [comment]
@gzm0 Any chance of getting a new release soon?
