### PR TITLE
Fix #24: Add custom console capture to Chrome.

### LINKED ISSUE #24: Chrome output explosion
When connecting to Chrome, running `testOnly`, between each test a blob akin to this is logged to console:

``` json
{"message":{"column":61,"executionContextId":1,"level":"log","line":374705,"parameters":[{"type":"string","value":""}],"source":"console-api","stackTrace":[{"columnNumber":61,"functionName":"$c_jl_JSConsoleBasedPrintStream.doWriteLine__p4__T__V","lineNumber":374705,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":12,"functionName":"$c_jl_JSConsoleBasedPrintStream.java$lang$JSConsoleBasedPrintStream$$printString__T__V","lineNumber":374690,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_jl_JSConsoleBasedPrintStream.println__O__V","lineNumber":374679,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":36,"functionName":"$c_s_Console$.println__O__V","lineNumber":165244,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":21,"functionName":"","lineNumber":7040,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":7,"functionName":"$c_s_Option.foreach__F1__V","lineNumber":303315,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":66,"functionName":"$s_Lteststate_run_ReportFormat$class__print__Lteststate_run_ReportFormat__Lteststate_run_Report__F1__V","lineNumber":7038,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":3,"functionName":"$c_Lteststate_run_ReportFormat$Default.print__Lteststate_run_Report__F1__V","lineNumber":140619,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":46,"functionName":"$c_Lteststate_run_Report.assert__Lteststate_run_Report$AssertionSettings__F1__V","lineNumber":299236,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":5,"functionName":"$c_LX_webapp_client_app_reqtable_XTableTest$$anonfun$runTest$1.apply__Ljapgolly_scalajs_react_ReactComponentM__V","lineNumber":273523,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_LX_webapp_client_app_reqtable_XTableTest$$anonfun$runTest$1.apply__O__O","lineNumber":273526,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Ljapgolly_scalajs_react_test_package$.japgolly$scalajs$react$test$package$$$undwithRenderedIntoDocument__O__F1__F1__F1__O","lineNumber":18099,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":53,"functionName":"$c_Ljapgolly_scalajs_react_test_package$ReactTestUtilsScalaExt$.withRenderedIntoDocument$extension1__Ljapgolly_scalajs_react_test_ReactTestUtils__Ljapgolly_scalajs_react_ReactComponentU__F1__O","lineNumber":18136,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":69,"functionName":"$c_LX_webapp_client_app_reqtable_XTableTest$.runTest__Lteststate_data_Sack__LX_webapp_base_data_Project__V","lineNumber":134009,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_LX_webapp_client_app_reqtable_XTableTest$.testImplicationSrcColumnEditor__V","lineNumber":134037,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":60,"functionName":"","lineNumber":273640,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction0.apply__O","lineNumber":167929,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":36,"functionName":"$c_Lutest_framework_TestThunkTree.run__sci_List__O","lineNumber":96425,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":77,"functionName":"$c_Lutest_framework_TestThunkTree.run__sci_List__O","lineNumber":96420,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":77,"functionName":"$c_Lutest_framework_TestThunkTree.run__sci_List__O","lineNumber":96420,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":458,"functionName":"","lineNumber":301894,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction0.apply__O","lineNumber":167929,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":47,"functionName":"$c_s_util_Try$.apply__F0__s_util_Try","lineNumber":100432,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":27,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$1$$anonfun$apply$3.apply__s_util_Try","lineNumber":301892,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$1$$anonfun$apply$3.apply__O","lineNumber":301902,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":39,"functionName":"$c_s_Option.fold__F0__F1__O","lineNumber":303287,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":29,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$1.apply__s_Option__s_util_Try","lineNumber":301848,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$1.apply__O__O","lineNumber":301857,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_s_util_Success.$$anonfun$3__p2__F1__O","lineNumber":349428,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":20,"functionName":"","lineNumber":349380,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction0.apply__O","lineNumber":167929,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":47,"functionName":"$c_s_util_Try$.apply__F0__s_util_Try","lineNumber":100432,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":27,"functionName":"$c_s_util_Success.map__F1__s_util_Try","lineNumber":349378,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":59,"functionName":"$s_s_concurrent_Future$class__$$anonfun$8__p0__s_concurrent_Future__s_concurrent_Promise__F1__s_util_Try__s_concurrent_Promise","lineNumber":7877,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":7831,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":27,"functionName":"$c_s_concurrent_impl_CallbackRunnable.run__V","lineNumber":166284,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":52,"functionName":"$c_s_concurrent_impl_CallbackRunnable.executeWithValue__s_util_Try__V","lineNumber":166308,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":18,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.dispatchOrAddCallback__p3__s_concurrent_impl_CallbackRunnable__V","lineNumber":386894,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.onComplete__F1__s_concurrent_ExecutionContext__V","lineNumber":386885,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$s_s_concurrent_Future$class__map__s_concurrent_Future__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":7828,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.map__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":386803,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":39,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.apply__s_concurrent_Future","lineNumber":301774,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.apply__O","lineNumber":301783,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":57,"functionName":"$c_s_concurrent_impl_Future$PromiseCompletingRunnable.liftedTree1$1__p1__s_util_Try","lineNumber":142234,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":108,"functionName":"$c_s_concurrent_impl_Future$PromiseCompletingRunnable.run__V","lineNumber":142230,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":53,"functionName":"$c_s_concurrent_impl_Future$.apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":99599,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":41,"functionName":"$c_s_concurrent_Future$.apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":99404,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":36,"functionName":"$c_Lutest_framework_TestTreeSeq.runFuture__F2__sc_Seq__sc_Seq__s_concurrent_Future__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":96511,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":95,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__Lutest_util_Tree__s_concurrent_Future","lineNumber":302155,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__O__O","lineNumber":302166,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":54,"functionName":"$c_s_Option.fold__F0__F1__O","lineNumber":303287,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":62,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future","lineNumber":301808,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":28,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.apply__s_concurrent_Future","lineNumber":301776,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.apply__O","lineNumber":301783,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":57,"functionName":"$c_s_concurrent_impl_Future$PromiseCompletingRunnable.liftedTree1$1__p1__s_util_Try","lineNumber":142234,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":108,"functionName":"$c_s_concurrent_impl_Future$PromiseCompletingRunnable.run__V","lineNumber":142230,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":53,"functionName":"$c_s_concurrent_impl_Future$.apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":99599,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":41,"functionName":"$c_s_concurrent_Future$.apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":99404,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":36,"functionName":"$c_Lutest_framework_TestTreeSeq.runFuture__F2__sc_Seq__sc_Seq__s_concurrent_Future__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":96511,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":95,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__Lutest_util_Tree__s_concurrent_Future","lineNumber":302155,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__O__O","lineNumber":302166,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":54,"functionName":"$c_s_Option.fold__F0__F1__O","lineNumber":303287,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":62,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future","lineNumber":301808,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":131,"functionName":"","lineNumber":302158,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":46,"functionName":"$s_s_concurrent_Future$class__$$anonfun$9__p0__s_concurrent_Future__s_concurrent_impl_Promise$DefaultPromise__F1__s_util_Try__O","lineNumber":7891,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":7841,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":27,"functionName":"$c_s_concurrent_impl_CallbackRunnable.run__V","lineNumber":166284,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":52,"functionName":"$c_s_concurrent_impl_CallbackRunnable.executeWithValue__s_util_Try__V","lineNumber":166308,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":18,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.dispatchOrAddCallback__p3__s_concurrent_impl_CallbackRunnable__V","lineNumber":386894,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.onComplete__F1__s_concurrent_ExecutionContext__V","lineNumber":386885,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$s_s_concurrent_Future$class__flatMap__s_concurrent_Future__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":7838,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.flatMap__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":386806,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":587,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__Lutest_util_Tree__s_concurrent_Future","lineNumber":302155,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__O__O","lineNumber":302166,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":54,"functionName":"$c_s_Option.fold__F0__F1__O","lineNumber":303287,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":62,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future","lineNumber":301808,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":131,"functionName":"","lineNumber":302158,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":46,"functionName":"$s_s_concurrent_Future$class__$$anonfun$9__p0__s_concurrent_Future__s_concurrent_impl_Promise$DefaultPromise__F1__s_util_Try__O","lineNumber":7891,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":7841,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":27,"functionName":"$c_s_concurrent_impl_CallbackRunnable.run__V","lineNumber":166284,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":52,"functionName":"$c_s_concurrent_impl_CallbackRunnable.executeWithValue__s_util_Try__V","lineNumber":166308,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":18,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.dispatchOrAddCallback__p3__s_concurrent_impl_CallbackRunnable__V","lineNumber":386894,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.onComplete__F1__s_concurrent_ExecutionContext__V","lineNumber":386885,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$s_s_concurrent_Future$class__flatMap__s_concurrent_Future__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":7838,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.flatMap__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":386806,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":587,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__Lutest_util_Tree__s_concurrent_Future","lineNumber":302155,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__O__O","lineNumber":302166,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":54,"functionName":"$c_s_Option.fold__F0__F1__O","lineNumber":303287,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":62,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future","lineNumber":301808,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":131,"functionName":"","lineNumber":302158,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":46,"functionName":"$s_s_concurrent_Future$class__$$anonfun$9__p0__s_concurrent_Future__s_concurrent_impl_Promise$DefaultPromise__F1__s_util_Try__O","lineNumber":7891,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":7841,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction1.apply__O__O","lineNumber":167958,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":27,"functionName":"$c_s_concurrent_impl_CallbackRunnable.run__V","lineNumber":166284,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":52,"functionName":"$c_s_concurrent_impl_CallbackRunnable.executeWithValue__s_util_Try__V","lineNumber":166308,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":18,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.dispatchOrAddCallback__p3__s_concurrent_impl_CallbackRunnable__V","lineNumber":386894,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.onComplete__F1__s_concurrent_ExecutionContext__V","lineNumber":386885,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$s_s_concurrent_Future$class__flatMap__s_concurrent_Future__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":7838,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$c_s_concurrent_impl_Promise$DefaultPromise.flatMap__F1__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":386806,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":587,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__Lutest_util_Tree__s_concurrent_Future","lineNumber":302155,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1$$anonfun$utest$framework$TestTreeSeq$$anonfun$$runChildren$1$2.apply__O__O","lineNumber":302166,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":54,"functionName":"$c_s_Option.fold__F0__F1__O","lineNumber":303287,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":62,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.utest$framework$TestTreeSeq$$anonfun$$runChildren$1__sc_Seq__sci_List__I__s_concurrent_Future__s_concurrent_Future","lineNumber":301808,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":28,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.apply__s_concurrent_Future","lineNumber":301776,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":15,"functionName":"$c_Lutest_framework_TestTreeSeq$$anonfun$runFuture$1.apply__O","lineNumber":301783,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":57,"functionName":"$c_s_concurrent_impl_Future$PromiseCompletingRunnable.liftedTree1$1__p1__s_util_Try","lineNumber":142234,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":108,"functionName":"$c_s_concurrent_impl_Future$PromiseCompletingRunnable.run__V","lineNumber":142230,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"$c_Lutest_ExecutionContext$RunNow$.execute__jl_Runnable__V","lineNumber":140938,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":53,"functionName":"$c_s_concurrent_impl_Future$.apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":99599,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":41,"functionName":"$c_s_concurrent_Future$.apply__F0__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":99404,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":36,"functionName":"$c_Lutest_framework_TestTreeSeq.runFuture__F2__sc_Seq__sc_Seq__s_concurrent_Future__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":96511,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":17,"functionName":"$c_Lutest_framework_TestTreeSeq.runAsync__F2__sc_Seq__sc_Seq__s_concurrent_ExecutionContext__s_concurrent_Future","lineNumber":96569,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":24,"functionName":"$c_Lutest_package$.runSuite__Lutest_framework_TestSuite__sc_Seq__AT__F1__F1__F2__F1__s_concurrent_Future","lineNumber":96649,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":31,"functionName":"$c_Lutest_runner_BaseRunner.runUTestTask__sc_Seq__sc_Seq__T__Lsbt_testing_EventHandler__s_concurrent_Future","lineNumber":140994,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":24,"functionName":"","lineNumber":141039,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction4.apply__O__O__O__O__O","lineNumber":168045,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":75,"functionName":"$c_Lutest_runner_Task.executeInternal__p1__Lsbt_testing_EventHandler__ALsbt_testing_Logger__s_concurrent_Future","lineNumber":141222,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_Lutest_runner_Task.execute__Lsbt_testing_EventHandler__ALsbt_testing_Logger__F1__V","lineNumber":141184,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$c_Lorg_scalajs_testinterface_internal_Slave.$$anonfun$9__p2__Lsbt_testing_Task__Lorg_scalajs_testinterface_internal_Slave$RemoteEventHandler__sjs_js_Array__V","lineNumber":110876,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":110760,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction0.apply__O","lineNumber":167929,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":47,"functionName":"$c_s_util_Try$.apply__F0__s_util_Try","lineNumber":100432,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":35,"functionName":"$c_Lorg_scalajs_testinterface_internal_Slave.execute__p2__sjs_js_Dynamic__V","lineNumber":110758,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":12,"functionName":"$c_Lorg_scalajs_testinterface_internal_Slave.$$anonfun$1__p2__T__F0__V","lineNumber":110801,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":110702,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":23,"functionName":"$c_sjsr_AnonFunction0.apply__O","lineNumber":167929,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":17,"functionName":"$c_Lorg_scalajs_testinterface_internal_Slave.allowSendRunnerMessage__p2__F0__O","lineNumber":110723,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V","lineNumber":110700,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":10,"functionName":"$c_Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V","lineNumber":25926,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":8,"functionName":"$c_Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V","lineNumber":25994,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":14,"functionName":"","lineNumber":25918,"scriptId":"49","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"},{"columnNumber":7,"functionName":"scalajsSeleniumComJSRunnerChannel.recvMessage","lineNumber":30,"scriptId":"46","url":"file:///tmp/1458617706149-0/comSetup.js"},{"columnNumber":72,"functionName":"","lineNumber":248,"scriptId":"68","url":""},{"columnNumber":33,"functionName":"callFunction","lineNumber":237,"scriptId":"68","url":""},{"columnNumber":23,"functionName":"","lineNumber":247,"scriptId":"68","url":""},{"columnNumber":3,"functionName":"","lineNumber":248,"scriptId":"68","url":""},{"columnNumber":140,"functionName":"InjectedScript._evaluateOn","lineNumber":878,"scriptId":"38","url":""},{"columnNumber":34,"functionName":"InjectedScript._evaluateAndWrap","lineNumber":811,"scriptId":"38","url":""},{"columnNumber":21,"functionName":"InjectedScript.evaluate","lineNumber":667,"scriptId":"38","url":""}],"text":"","timestamp":1458617712.07702,"type":"log","url":"file:///tmp/1458617706149-0/webapp-client-test-fastopt.js"}}
```

and then at the end , a final:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
Failed to load resource: net::ERR_FILE_NOT_FOUND
```

FYI using Chrome 49.0.2623.75.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Use the same console capture as Firefox in Chrome (formerly called hijacked console).

### CODE REVIEW

**Comment by nicolasstucki** [comment]
@japgolly could you run this PR with your setup to see if this does fix the whole issue #24 for you. Thanks.

**Comment by japgolly** [comment]
@nicolasstucki kk, will try now

**Comment by japgolly** [comment]
@nicolasstucki Ok, 1 yes and 2 no.

**Yes:** I now see the test output in SBT without those huge json blobs. :+1: 

**No₁:** I get a new error in my tests. This appears before any test output and marks one of my tests as failed:

```
org.openqa.selenium.WebDriverException: unknown error: onReceive is not a function
  (Session info: chrome=49.0.2623.108)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.4.5-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.5-1-ARCH', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a), userDataDir=/tmp/.com.google.Chrome.QWpGdM}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.108, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a143a7a2e4bfa1ae2f1da3d9d3e6bfdb
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
    at org.scalajs.jsenv.selenium.SeleniumComJSRunner.send(SeleniumComJSRunner.scala:24)
    at org.scalajs.testadapter.ScalaJSRunner.createSlave(ScalaJSRunner.scala:184)
    at org.scalajs.testadapter.ScalaJSRunner.getSlave(ScalaJSRunner.scala:143)
    at org.scalajs.testadapter.ScalaJSTask.execute(ScalaJSTask.scala:33)
    at sbt.TestRunner.runTest$1(TestFramework.scala:76)
    at sbt.TestRunner.run(TestFramework.scala:85)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
    at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
    at sbt.TestFunction.apply(TestFramework.scala:207)
    at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
    at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] Could not run test japgolly.blah.blah.BlahTest: org.openqa.selenium.WebDriverException: unknown error: onReceive is not a function
[error]   (Session info: chrome=49.0.2623.108)
[error]   (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.4.5-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
[error] Command duration or timeout: 11 milliseconds
[error] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
[error] System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.5-1-ARCH', java.version: '1.8.0_77'
[error] Driver info: org.openqa.selenium.chrome.ChromeDriver
[error] Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a), userDataDir=/tmp/.com.google.Chrome.QWpGdM}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.108, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
[error] Session ID: a143a7a2e4bfa1ae2f1da3d9d3e6bfdb
```

**No₂:** Running `test` in _scala-js-env-selenium_, most tests pass but I consistently get the following error. (Which is weird because I see that Travis CI.)

```
org.openqa.selenium.WebDriverException: scalajsPopCapturedConsoleLogs is not defined
Command duration or timeout: 13 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.5-1-ARCH', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.1, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 59f84ad7-b7eb-4382-9897-ff373a92ff5d
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
    at org.scalajs.jsenv.selenium.BrowserDriver.processNextLogBatch$1(BrowserDriver.scala:46)
    at org.scalajs.jsenv.selenium.BrowserDriver.processConsoleLogs(BrowserDriver.scala:55)
    at org.scalajs.jsenv.selenium.AbstractSeleniumJSRunner.runAllScripts(AbstractSeleniumJSRunner.scala:42)
    at org.scalajs.jsenv.selenium.SeleniumRunner.run(SeleniumRunner.scala:15)
    at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:66)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56.apply(ScalaJSPluginInternal.scala:705)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56.apply(ScalaJSPluginInternal.scala:688)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: scalajsPopCapturedConsoleLogs is not defined
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.5-1-ARCH', java.version: '1.8.0_77'
Driver info: driver.version: unknown
    at <anonymous class>.anonymous(about:neterror?e=connectionFailure&u=http%3A//localhost%3A8080/tmp/scalajsRun.html&c=UTF-8&f=regular&d=Firefox%20can%27t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A8080. line 69 > Function:1)
    at <anonymous class>.handleEvaluateEvent(about:neterror?e=connectionFailure&u=http%3A//localhost%3A8080/tmp/scalajsRun.html&c=UTF-8&f=regular&d=Firefox%20can%27t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A8080.:69)
[error] (seleniumJSHttpEnvTest/test:loadedTestFrameworks) org.openqa.selenium.WebDriverException: scalajsPopCapturedConsoleLogs is not defined
[error] Command duration or timeout: 13 milliseconds
[error] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
[error] System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.5-1-ARCH', java.version: '1.8.0_77'
[error] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[error] Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0.1, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
[error] Session ID: 59f84ad7-b7eb-4382-9897-ff373a92ff5d
```

**Comment by nicolasstucki** [comment]
@japgolly, I have now tested the the last fixes in a machine with Ubuntu using the same Chrome and chromedriver version that you have. I did not have the issues No1 and No2. Could you check if it also works in your setup. Thanks.

PS: I suggest an `sbt clean` before running the tests.

**Comment by nicolasstucki** [comment]
It seems I was able to reproduce the first issue on Travis (https://travis-ci.org/scala-js/scala-js-env-selenium/jobs/119553881) it looks like it only happens on Scala 2.10 with JDK 7.

PS: This issue is not linked to the changes in this PR.

**Comment by japgolly** [comment]
@nicolasstucki Just tried again with latest from your fork (805828840eb75398c17c6c0377d9cbe0e48a08f5). Both problems persist.

Also I'm using Scala 2.11.8 and JDK 1.8.0_77.

**Comment by japgolly** [comment]
I just realised that lots of `/tmp/.com.google.Chrome.XXXXXX` directories exist. I wiped them all, tested this again and it works! Maybe the directories left behind from running with 0.1.1 were affecting the runs with 0.1.2-SNAPSHOT. Either way, those directories should be cleared after tests complete (right?). I'll create a new issue.

**Comment by japgolly** [comment]
I spoke too soon. After I clear all directories and run again I got the same `unknown error: onReceive is not a function` error. It must be a race condition (I have 8 cores) which explains why it isn't reproducible on Travis CI.

**Comment by nicolasstucki** [comment]
I identified the probable cause of the race condition for `onReceive is not a function` and created issue #33 for it. 

Given that this PR fixes the issue mentioned in #24 and all other issues mentioned above have a PR we should move all further discussions to their respective PR.

File: project/BinaryIncompatibilities.scala [hunk 1]
```diff
@@ -3,5 +3,6 @@ import com.typesafe.tools.mima.core.ProblemFilters._
 
 object BinaryIncompatibilities {
   val SeleniumJSEnv = Seq(
+    ProblemFilters.exclude[MissingMethodProblem]("org.scalajs.jsenv.selenium.SeleniumBrowser.setupConsoleCapture")
```
Comment (sjrd) [inline project/BinaryIncompatibilities.scala]: We typically break after `(` and indent 4 spaces in `BinIncompats.scala`.

Comment (sjrd) [inline project/BinaryIncompatibilities.scala]: There should also be a comment saying whether this is a breaking change or not.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/BrowserDriver.scala [hunk 2]
```diff
@@ -1,13 +1,22 @@
...
 
+import scala.annotation.tailrec
+import scala.collection.JavaConversions._
+
 abstract class BrowserDriver {
 
+  private final val popCapturedConsoleScript = {
+    "var callback = arguments[arguments.length - 1];" +
+    "callback(this.scalajsPopCapturedConsoleLogs());"
+  }
```
Comment (sjrd) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/BrowserDriver.scala]: Looks like this should be in the companion object.

**Comment by sjrd** [comment]
That's all.

**Comment by nicolasstucki** [comment]
Rebased

**Comment by sjrd** [comment]
LGTM
