### PR TITLE
Fix #14: Fetch Firefox console logs by parts.

### LINKED ISSUE #14: Timing out when fetching the console output in Firefox.
I ran a full clean build + test today with selenium enabled and the tests timed out.

```
root> last webapp-client/test:test
org.openqa.selenium.UnhandledAlertException: Unexpected modal dialog (text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: file:///tmp/1458267039897-0/webapp-client-test-fastopt.js:227864): A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: file:///tmp/1458267039897-0/webapp-client-test-fastopt.js:227864
Build info: version: '2.49.1', revision: '808c23b0963853d375cbe54b90bbd052e2528a54', time: '2016-01-21 09:37:52'
System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.1-2-ARCH', java.version: '1.8.0_74'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 3df6315e-cba9-4d45-8b0b-747ec1ec275f
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.createUnhandledAlertException(ErrorHandler.java:187)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:154)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
    at org.scalajs.jsenv.selenium.Firefox$FirefoxDriver.newConsoleLogsIterator(Firefox.scala:51)
    at org.scalajs.jsenv.selenium.BrowserDriver.processConsoleLogs(BrowserDriver.scala:40)
    at org.scalajs.jsenv.selenium.SeleniumComJSRunner.send(SeleniumComJSRunner.scala:26)
    at org.scalajs.testadapter.ScalaJSTask.execute(ScalaJSTask.scala:45)
    at sbt.TestRunner.runTest$1(TestFramework.scala:76)
    at sbt.TestRunner.run(TestFramework.scala:85)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
    at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
    at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
    at sbt.TestFunction.apply(TestFramework.scala:207)
    at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
    at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] Could not run test blah....Test: org.openqa.selenium.UnhandledAlertException: Unexpected modal dialog (text: A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
[error] 
[error] Script: file:///tmp/1458267039897-0/webapp-client-test-fastopt.js:227864): A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
[error] 
[error] Script: file:///tmp/1458267039897-0/webapp-client-test-fastopt.js:227864
[error] Build info: version: '2.49.1', revision: '808c23b0963853d375cbe54b90bbd052e2528a54', time: '2016-01-21 09:37:52'
[error] System info: host: 'golly-desktop', ip: '192.168.3.20', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.1-2-ARCH', java.version: '1.8.0_74'
[error] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[error] Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=45.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
[error] Session ID: 3df6315e-cba9-4d45-8b0b-747ec1ec275f
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd.

**Comment by sjrd** [comment]
Are we sure this actually fixes #14?
@japgolly Would you be able to test whether this solves your issue? (you can probably easily test with a `publishLocal` of this branch)

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/Firefox.scala [hunk 1]
```diff
@@ -33,10 +36,21 @@ object Firefox extends SeleniumBrowser {
...
+        |      var log = [];
+        |      while (currentLogIndex < console_log_hijack.length &&
+        |          log.length < 1024) {
+        |        log.push(console_log_hijack[currentLogIndex]);
+        |        currentLogIndex++;
+        |      }
+        |      if (console_log_hijack.length == currentLogIndex) {
+        |        console_log_hijack = [];
+        |        currentLogIndex = 0;
+        |      }
```
Comment (sjrd) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/Firefox.scala:51]: Why not remove all the entries from `console_log_hijack` that are sent, rather than maintaining a "global" `currentLogIndex`?

**Comment by sjrd** [comment]
That's all.

File: seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/Firefox.scala (hunk 1 above)
Comment (nicolasstucki) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/Firefox.scala:51]: That was my first approach, but modifying `console_log_hijack` has linear time and hence ends up timing out in the same cases that the previous solution did. Additionally, each time the console logs are fetched `scalajsPopHijackedConsoleLog` is called in a loop until the result is empty, at which point the `console_log_hijack` is reinitialized.

Comment (sjrd) [inline seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/Firefox.scala:51]: OK.

**Comment by nicolasstucki** [comment]
It fixed the issue when the logs are too long. In my tests I had the same exception. There is still the potential for timeouts with every call to `getWebDriver.executeScript` for which there is a more involved solution using `getWebDriver.executeAsyncScript` for which there is a way to disable the timeouts.

**Comment by sjrd** [comment]
LGTM
